# Screen dimensions
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# Maze settings
TILE_SIZE = 20
MAZE_WIDTH = SCREEN_WIDTH // TILE_SIZE
MAZE_HEIGHT = SCREEN_HEIGHT // TILE_SIZE

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)

# Persona Colors
CHIRON_COLOR = BLUE
ERIDA_COLOR = RED
MORA_COLOR = (128, 0, 128) # Purple

PLAYER_COLOR = RED
WALL_COLOR = BLACK
HINT_COLOR = GREEN
PATH_COLOR = BLUE

# Player settings
PLAYER_SPEED = 5

# Persona keys
PERSONA_CHIRON = '1'
PERSONA_ERIDA = '2'
PERSONA_MORA = '3'
